### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by Tawannaer** [xiaochus/YOLOv3#20]
I found an error in this code. I am looking forward to the author's reply   thanks
 File "demo.py", line 152, in <module>
    image = detect_image(image, yolo, all_classes)
  File "demo.py", line 90, in detect_image
    boxes, classes, scores = yolo.predict(pimage, image.shape)
  File "C:\Users\Administrator\Desktop\YOLOv3-master\model\yolo_model.py", line 209, in predict
    boxes, classes, scores = self._yolo_out(outs, shape)
  File "C:\Users\Administrator\Desktop\YOLOv3-master\model\yolo_model.py", line 158, in _yolo_out
    b, c, s = self._process_feats(out, anchors, mask)
  File "C:\Users\Administrator\Desktop\YOLOv3-master\model\yolo_model.py", line 54, in _process_feats
    box_wh = box_wh * anchors_tensor
ValueError: operands could not be broadcast together with shapes (13,13,2) (1,1,3,2)
![qq 20181214105101](https://user-images.githubusercontent.com/37647733/49981082-40f5ee00-ff91-11e8-81be-24abab3931b9.png)

**Comment by Tawannaer** [comment]
@xiaochus

**Comment by xiaochus** [comment]
I did not have this problem in the local test, whether you are using the old code?

**Comment by Tawannaer** [comment]
Thank you for your reply, I have updated the code. But there is still this problem. If you have a better discovery, please contact me. thank you very much

**Comment by cansik** [comment]
Same issue here when using plaidml as backend (can not test it with tensorflow on mac). @aichijing How did you fix this?

```bash
python3 demo_plaid.py
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_amd_radeon_pro_460_compute_engine.0"
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:269: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
dog.jpg
INFO:plaidml:Analyzing Ops: 164 of 1106 operations complete
INFO:plaidml:Analyzing Ops: 346 of 1106 operations complete
INFO:plaidml:Analyzing Ops: 545 of 1106 operations complete
INFO:plaidml:Analyzing Ops: 836 of 1106 operations complete
INFO:plaidml:Analyzing Ops: 1056 of 1106 operations complete
Traceback (most recent call last):
  File "demo_plaid.py", line 155, in <module>
    image = detect_image(image, yolo, all_classes)
  File "demo_plaid.py", line 93, in detect_image
    boxes, classes, scores = yolo.predict(pimage, image.shape)
  File "YOLOv3/model/yolo_model.py", line 208, in predict
    boxes, classes, scores = self._yolo_out(outs, shape)
  File "YOLOv3/model/yolo_model.py", line 157, in _yolo_out
    b, c, s = self._process_feats(out, anchors, mask)
  File "YOLOv3/model/yolo_model.py", line 53, in _process_feats
    box_wh = box_wh * anchors_tensor
ValueError: operands could not be broadcast together with shapes (13,13,2) (1,1,3,2)
```

**Comment by amichayfeldman** [comment]
what is your input image's shape?

i opened a new issue about mistake i found in the code. look there and maybe it can help you.
