### ISSUE TITLE
could not create a dilated convolution forward descriptor

### ISSUE THREAD

**Issue by nm46nm** [xiaochus/YOLOv3#24]
I have the following problem when running "demo.py", could anyone tell me how to solve it?
`
WARNING:tensorflow:From C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
dog.jpg
Traceback (most recent call last):

  File "<ipython-input-1-57223e754127>", line 1, in <module>
    runfile('C:/Users/10137/Desktop/learn/python/yolov3_keras/demo.py', wdir='C:/Users/10137/Desktop/learn/python/yolov3_keras')

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras/demo.py", line 152, in <module>
    image = detect_image(image, yolo, all_classes)

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras/demo.py", line 90, in detect_image
    boxes, classes, scores = yolo.predict(pimage, image.shape)

  File "C:\Users\10137\Desktop\learn\python\yolov3_keras\model\yolo_model.py", line 212, in predict
    outs = self._yolo.predict(image)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training.py", line 1169, in predict
    steps=steps)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

AbortedError: Operation received an exception:Status: 3, message: could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111
	 [[{{node conv2d_2/convolution}}]]
`

**Comment by gdut3118007086** [comment]
do you solve the problem? i meet the same problem

**Comment by MisbahAF** [comment]
I meet the same problem too..... I downgraded the Keras version but still getting the same error....
